package com.example.todocloud.datasynchronizer;

import android.util.Log;

import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.example.todocloud.app.AppConfig;
import com.example.todocloud.app.AppController;
import com.example.todocloud.datastorage.DbConstants;
import com.example.todocloud.datastorage.DbLoader;
import com.example.todocloud.helper.InstallationIdHelper;
import com.example.todocloud.helper.OnlineIdGenerator;

import org.json.JSONException;
import org.json.JSONObject;

public class UserDataSynchronizer extends DataSynchronizer {

  private static final String TAG = UserDataSynchronizer.class.getSimpleName();

  private OnRegisterUserListener onRegisterUserListener;
  private OnLoginUserListener onLoginUserListener;
  private DbLoader dbLoader;

  public UserDataSynchronizer(DbLoader dbLoader) {
    this.dbLoader = dbLoader;
  }

  public void setOnRegisterUserListener(OnRegisterUserListener onRegisterUserListener) {
    this.onRegisterUserListener = onRegisterUserListener;
  }

  public void setOnLoginUserListener(OnLoginUserListener onLoginUserListener) {
    this.onLoginUserListener = onLoginUserListener;
  }

  public void registerUser(
      final String user_online_id,
      final String name,
      final String email,
      final String password,
      final long _id
  ) {
    String tag_json_object_request = "request_register";

    JSONObject jsonRequest = new JSONObject();
    try {
      putUserData(user_online_id, name, email, password, jsonRequest);
    } catch (JSONException e) {
      e.printStackTrace();
      String errorMessage = "JSONException";
      onRegisterUserListener.onSyncError(errorMessage);
    }

    JsonObjectRequest registerRequest = new JsonObjectRequest(
        JsonObjectRequest.Method.POST,
        AppConfig.URL_REGISTER,
        jsonRequest,
        new Response.Listener<JSONObject>() {

          @Override
          public void onResponse(JSONObject response) {
            Log.d(TAG, "Register Response: " + response);
            try {
              boolean error = response.getBoolean("error");

              if (!error) {
                onRegisterUserListener.onFinishRegisterUser();
              } else {
                String message = response.getString("message");
                if (message != null) {
                  if (message.contains("Oops! An error occurred while registereing")) {
                    handleError();
                  } else {
                    onRegisterUserListener.onSyncError(message);
                  }
                }
              }
            } catch (JSONException e) {
              e.printStackTrace();
              String errorMessage = "JSONException";
              onRegisterUserListener.onSyncError(errorMessage);
            }
          }

          /**
           * Generally the cause of error is, that the userOnlineId generated by the client is
           * already registered in the remote database. In this case, it generate a different
           * userOnlineId, and send the registration request again.
           */
          private void handleError() {
            InstallationIdHelper.getNewInstallationId();
            String new_user_online_id = OnlineIdGenerator.generateOnlineId(
                DbConstants.User.DATABASE_TABLE,
                _id
            );
            registerUser(new_user_online_id, name, email, password, _id);
          }

        },
        new Response.ErrorListener() {

          @Override
          public void onErrorResponse(VolleyError error) {
            String errorMessage = error.getMessage();
            Log.e(TAG, "Register Error: " + errorMessage);
            if (errorMessage != null) {
              onRegisterUserListener.onSyncError(errorMessage);
            }
          }

        }
    );

    AppController.getInstance().addToRequestQueue(registerRequest, tag_json_object_request);
  }

  private void putUserData(
      String user_online_id,
      String name,
      String email,
      String password,
      JSONObject jsonRequest
  ) throws JSONException {
    jsonRequest.put("user_online_id", user_online_id);
    jsonRequest.put("name", name);
    jsonRequest.put("email", email);
    jsonRequest.put("password", password);
  }

  public interface OnRegisterUserListener {
    void onFinishRegisterUser();
    void onSyncError(String errorMessage);
  }

  public interface OnLoginUserListener {
    void onFinishLoginUser();
    void onSyncError(String errorMessage);
  }

}
